# Linux Build Configuration for Travis

language: cpp

os:
  - linux

# Use Ubuntu 14.04 LTS (Trusty) as the Linux testing environment.
sudo: required
dist: trusty

env:
  matrix:
    # Each line is a set of environment variables set before a build.
    # Thus each line represents a different build configuration.
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

compiler:
  - clang
  - gcc

cache:
  apt: true

branches:
  only:
    - master

addons:
  apt:
    packages:
      - ninja-build

before_script:
  - git clone https://github.com/google/googletest.git external/googletest

script:
  - mkdir build && cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - ninja
    # Be nice and only output if there are failures.
  - ./UnitSPIRV --gtest_break_on_failure &> log || cat log


notifications:
  email:
    recipients:
      - antiagainst@google.com
      - awoloszyn@google.com
      - deki@google.com
      - dneto@google.com
      - qining@google.com
    on_success: change
    on_failure: always
